const Err = {
    'Caller from other contract': '0',
    'Mint error: invalid token ID': '1',
    'Random error': '2',
    'No more gift NFTs available': '3',
    'Not started yet': '4',
    'The quantity must be greater than 0': '5',
    'Sold out': '6',
    'Not enough stock': '7',
    'Limited holdings': '8',
    'Merkleroot is not set': '9',
    'You are not on the whitelist': '10',
    'Only mint once': '11',
    'The maximum is 2': '12',
    'Run out of free NFTs': '13',
    'Need more ETH': '14',
    'Already set': '15',
    'Quantity limit': '16',
    'Invalid requestId': '17',
    Refunded: '18',
    'Repeated action': '19',
    'Presale sold out': '20',
    'Not enough for auction': '21',
    'Not enough for sale': '22',
    'Refund failed': '23',
    'Unknown address': '24',
    'Can not be duplicated': '25',
    'Some of them are not allowed to be synthesized': '26',
    'Some of them do not belong to you': '27',
    'Can not synthesis': '28',
    'Insufficient balance': '29',
    'Game already initiated': '30',
    'Can not initiate game yet': '31',
    'Invalid reqId': '32',
    'LeopardGod address not set': '33',
    'Game not initiated': '34',
    'Not yet game time': '35',
    'LeopardGod NFTs do not exist': '36',
    'Not yet started': '37',
    'Paid out': '38',
    'You did not win an award': '39',
    'Some are not super crowns': '40',
    'You cant do this': '41',
    'Transfer failed': '42',
};

const rErr: Record<string, string> = Object.entries(Err).reduce(
    (pre, [val, key]) => ({ ...pre, [key]: val }),
    {}
);

export default rErr;
